# fly.toml app configuration file generated for apex-legends-player-monitor on 2024-08-29T00:39:02+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'apex-legends-player-monitor'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
